// Generated by CoffeeScript 1.3.3
(function() {

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Music Arena.Home'
    });
  };

  exports.login = function(req, res) {
    return res.render('login', {
      title: 'Music Arena. Log in'
    });
  };

}).call(this);
